[package]
name = "jenga"
version = "0.1.0"
edition = "2021"

[features]
rate_limit = []
retry = []
retry_wait = ["dep:tokio"]
timeout = ["dep:tokio"]

[dependencies]
tokio = { version = "1.42.0", optional = true, features = ["rt", "macros", "time"] }

[dev-dependencies]
tokio = { version = "1.42.0", features = ["rt", "macros"] }